---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
#-------------------APP
    - yum:
        name: "{{ item }}"
        state: present
      loop:
         - python-setuptools
         - python3
         - screen

    - pip:
        executable: /usr/bin/pip3
        name: virtualenv
        state: present

    - unarchive:
        src: app.tar.gz
        copy: yes
        dest: /opt

    - shell:
        cmd: /usr/bin/pip3 install -r /opt/app/requirements.txt

    - file:
        src: /opt/app/myapp.service
        dest: /usr/lib/systemd/system/myapp.service
        state: link

    - template:
        src: env_template.j2
        dest: /opt/app/.env

    - systemd:
        daemon_reload: yes
        name: myapp
        enabled: yes
        state: started

    - shell:
        cmd: "iptables -I INPUT 1 -p tcp -m tcp --dport 5000 -j ACCEPT"
