---
- name: Deploy applications servers
  hosts: node_app
  become: yes
  gather_facts: yes

  tasks:
  - name: set hostname
    hostname:
      use: systemd
      name: "{{ hostname }}"

  - name: install necessary packages
    yum:
      name: "{{ item }}"
      state: present
    loop:
       - python-setuptools
       - python3
       - screen

  - name: unarchive application
    unarchive:
      src: app.tar.gz
      copy: yes
      dest: /opt

  - name: install application dependencies
    shell:
      cmd: /usr/bin/pip3 install -r /opt/app/requirements.txt

  - name: create symlink to systemd-service unit of application
    file:
      src: /opt/app/myapp.service
      dest: /usr/lib/systemd/system/myapp.service
      state: link

  - name: generate .env file from template and put to application directory
    template:
      src: env_template.j2
      dest: /opt/app/.env

  - name: enable and start application systemd-unit
    systemd:
      daemon_reload: yes
      name: myapp
      enabled: yes
      state: started

  - name: allow inbound traffic to 5000 port from bouncer ip address
    shell:
      cmd: "-A INPUT -s {{ bouncer_ip }}/32 -p tcp -m tcp --dport 5000 -j ACCEPT"
