---
- name: Deploy bouncer server
  hosts: haproxy
  become: yes
  gather_facts: no

  tasks:
  - name: package HAProxy install
    yum:
      name: "{{ item }}"
      state: present
    loop:
       - haproxy

  - name: generation haproxy.cfg file and put to location
    template:
      src: haproxy_template.j2
      dest: /etc/haproxy/haproxy.cfg

  - name: enable and start HAProxy service
    systemd:
      name: haproxy
      enabled: yes
      state: started


  - name: allow inbound traffic to 5000 port
    shell:
      cmd: "iptables -I INPUT 1 -p tcp -m tcp --dport 5000 -j ACCEPT"