---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
#-------------------BOUNCER

    - yum:
        name: "{{ item }}"
        state: present
      loop:
         - haproxy

    - systemd:
        name: haproxy
        enabled: yes
        state: started

    - template:
        src: haproxy.j2
        dest: /etc/haproxy/haproxy.cfg

    - shell:
        cmd: "iptables -I INPUT 1 -p tcp -m tcp --dport 5000 -j ACCEPT"