---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
#-------------------DATABASE
    - unarchive:
        src: app.tar.gz
        copy: yes
        dest: /tmp/appbuild        

    # - file:
    #     src: /opt/app/myapp.service
    #     dest: /usr/lib/systemd/system/myapp.service
    #     state: link
    #   when: "'node_app' in group_names"

    # - template:
    #     src: env_template.j2
    #     dest: /opt/app/.env
    #   when: "'node_app' in group_names"

    - yum:
        name: "{{ item }}"
        state: present
      loop:
         - yum-utils
         - mariadb-server

    - shell:
        cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - yum:
        name: "{{ item }}"
        state: present
      loop:
         - docker-ce 
         - docker-ce-cli 
         - containerd.io

    - systemd:
        name: docker
        enabled: yes
        state: started

    - shell:
        cmd: cd /tmp/appbuild && docker build -t apitest:0.2 .
      ignore_errors: yes

    - file:
        path: /opt/registry
        state: directory

    - shell:
        cmd: docker run -d -p 5099:5099 --restart=always --name registry -v /opt/registry:/var/lib/registry registry:2
      ignore_errors: yes

    - systemd:
        name: mariadb
        enabled: yes
        state: started

    - copy:
        src: db.sql
        dest: /tmp/
      tags: files

    - shell:
        cmd: mysql < /tmp/db.sql && rm /tmp/db.sql

    - shell:
        cmd: "iptables -I INPUT 1 -s {{ item }} -p tcp -m tcp --dport 3306 -j ACCEPT"
      loop: "{{ allowed_ip|flatten(levels=1) }}"

    - shell:
        cmd: "iptables -I INPUT 1 -s {{ item }} -p tcp -m tcp --dport 5099 -j ACCEPT"
      loop: "{{ allowed_ip|flatten(levels=1) }}"